### ISSUE TITLE
Android virtual device: com.google.android.gms.common.GooglePlayServicesNotAvailableException

### ISSUE THREAD

**Issue by AE1NS** [sparkfabrik/capacitor-plugin-idfa#11]
When I run this on a virtual device in Android Studio, the whole app crashes. I get a `GooglePlayServicesNotAvailableException` and this line causes the crash:
`Log.e("Idfa", Objects.requireNonNull(e.getMessage()));`
Because `getMessage` returns null and `Objects.requireNonNull` throws another Exception afterwards.

**Comment by edodusi** [comment]
Thanks for the report, it should be enough to just catch the exception so I'm marking this as goof first contribution

**Comment by AE1NS** [comment]
This will be solved with this pr https://github.com/sparkfabrik/capacitor-plugin-idfa/pull/16
