### ISSUE TITLE
Permission Popup doesn't open on iOS 15.6 or higher. 

### ISSUE THREAD

**Issue by 3xpr** [sparkfabrik/capacitor-plugin-idfa#12]
### Subject of the issue
The getAdvertisingInfo() function does not open the popup on devices with iOS 15 or higher. 

### Your environment
iPhone 13 Pro Max - iOS 15.6
@sparkfabrik/capacitor-plugin-idfa@3.0.1
@ionic/angular@5.9.4
@ionic/core@5.9.4

### Steps to reproduce
Run an app with the plugin implemented on a device with iOS 15 or newer. 

### Expected behaviour
Displaying the AppTrackingTransparency popup where the user can deny or accept tracking. 

### Actual behaviour
The popup does not open. 

### Proposed Solution
I have no experience developing plugins or coding in SWIFT so take my suggestion with a large pinch of salt. 
However, I managed to get the popup to appear by adding 
`if #available(iOS 15, * ) {`
as an additional if statement in "Plugin.Swift" with identical content to 
`if #available(iOS 14, * ) { `

In my understanding, the #available statement should be understood as iOS 14 and higher, however on my devices it does not behave this way. 

### Code of my Plugin.swift file that works on iOS 15
`import Foundation
import Capacitor
import AdSupport
import AppTrackingTransparency

/**
 * Please read the Capacitor iOS Plugin Development Guide
 * here: https://capacitorjs.com/docs/plugins/ios
 */
@objc(Idfa)
public class Idfa: CAPPlugin {

    @objc func getAdvertisingInfo(_ call: CAPPluginCall) {
        if #available(iOS 15, * ) {
            ATTrackingManager.requestTrackingAuthorization { status in
                switch status {
                    case .authorized:
                        // Tracking authorization dialog was shown
                        // and we are authorized
                        call.resolve([
                            "id": ASIdentifierManager.shared().advertisingIdentifier.uuidString,
                            "isAdTrackingLimited": false
                        ])
                    case .denied:
                        // Tracking authorization dialog was
                        // shown and permission is denied
                        call.reject("Tracking denied")
                    case .notDetermined:
                        // Tracking authorization dialog has not been shown
                        call.reject("Not Determined")
                    case .restricted:
                        call.reject("Restricted")
                    @unknown default:
                        call.reject("Unknown")
                }
            }
        } else if #available(iOS 14, * ) {
            ATTrackingManager.requestTrackingAuthorization { status in
                switch status {
                    case .authorized:
                        // Tracking authorization dialog was shown
                        // and we are authorized
                        call.resolve([
                            "id": ASIdentifierManager.shared().advertisingIdentifier.uuidString,
                            "isAdTrackingLimited": false
                        ])
                    case .denied:
                        // Tracking authorization dialog was
                        // shown and permission is denied
                        call.reject("Tracking denied")
                    case .notDetermined:
                        // Tracking authorization dialog has not been shown
                        call.reject("Not Determined")
                    case .restricted:
                        call.reject("Restricted")
                    @unknown default:
                        call.reject("Unknown")
                }
            }
        } else {
            call.resolve([
                "id": ASIdentifierManager.shared().advertisingIdentifier.uuidString,
                "isAdTrackingLimited": false
            ])
        }
    }    
}
`

Edit: Formatting and spelling.

**Comment by 3xpr** [comment]
Turns out, all I needed was to run pod install inside the ios/app directory. 
Not sure why this does not work out of the box, but would be cool if that could be done at some point. 

Apologies for any trouble 🙏

**Comment by edodusi** [comment]
Yes pod install is required, no need to apologize ;)
