### ISSUE TITLE
Capacitor 4 support

### ISSUE THREAD

**Issue by dtarnawsky** [sparkfabrik/capacitor-plugin-idfa#15]
Any chance this plugin could be updated to support Capacitor 4?

Targeting Android 12 is a requirement for the Google Play store in November (and for new apps since August) so having a Capacitor 4 compatible version is important. There is a tool to help out with adding Capacitor 4 support for a plugin: https://github.com/rdlabo-team/capacitor-plugin-to-v4.

**Comment by edodusi** [comment]
Thanks @dtarnawsky, we are open to contributions so feel free to open a PR to add this feature, it will be indeed helpful

**Comment by AE1NS** [comment]
https://github.com/sparkfabrik/capacitor-plugin-idfa/pull/16
