### ISSUE TITLE
Feature request: getTrackingStatus() function 

### ISSUE THREAD

**Issue by KirstenStake** [sparkfabrik/capacitor-plugin-idfa#25]
Feature request for an additional function which would return the tracking status of the user. 
```
type IOSAppTrackingStatus =
  | 'authorized'
  | 'denied'
  | 'unrequested'
  | 'restricted';

```
We have run into a few use cases where we need to know the current user's tracking status before proceeding with either the native prompt or a different in-app experience. Also this will allow us to know if down the line the user has changed any of their permissions via their phone's settings, in order for us to show the native prompt journeys again.

**Comment by edodusi** [comment]
Hu @KirstenStake , please use the community plugin https://github.com/capacitor-community/advertising-id
